name: flutter_soloud
description: >-
  Flutter audio plugin using SoLoud library and FFI.
  It provides player, basic capture from microphone, 3D audio and more.
version: 1.2.4
issue_tracker: https://github.com/alnitak/flutter_soloud/issues
homepage: https://github.com/alnitak/flutter_soloud
maintainer: Marco Bavagnoli (@lildeimos)
platforms:
  android:
  ios:
  linux:
  macos:
  windows:
topics:
  - audio
  - player
  - games

screenshots:
  - description: "audio FFT data"
    path: img/screenshot.png

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

  #https://pub.dev/packages/ffi
  ffi: ^2.0.2
  #https://pub.dev/packages/http
  http: ^1.1.0
  #https://pub.dev/packages/path_provider

  path_provider: ^2.1.1
  path_provider_aurora:
    git:
      url: https://gitlab.com/omprussia/flutter/flutter-plugins.git
      ref: master
      path: packages/path_provider/path_provider_aurora

  
  plugin_platform_interface: ^2.1.5

dev_dependencies:
  #https://pub.dev/packages/ffigen
  ffigen: ^9.0.1
  flutter_test:
    sdk: flutter
  
  very_good_analysis: ^5.1.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true


